language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

  install:
    - pip install -r requirements.txt
    - cp conf.py.example conf.py

script:
  - python cowrie-logviewer.py test
